
name: Deploy Business app web release
on:
  push:
    branches: [master]
    

jobs:

  build-staging:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone Flutter repository with stable channel
      uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '3.3.9'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build -v web --release
    - name: Deploy to Netlify
      uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        NETLIFY_AUTH_TOKEN: WA2Ik4YjneZhAgOAYehgVQMXCAGmLoQTscR2L3CgpI4
        NETLIFY_DEPLOY_TO_PROD: false
        NETLIFY_SITE_ID: c7c11cd0-a011-4a7b-a083-2e06c656376d
        BUILD_COMMAND: flutter build -v web --release 
        INSTALL_COMMAND: flutter pub get
        BUILD_DIRECTORY: 'build/web'
    
  

