
name: Deploy Business app web release
on:
  push:
    branches: [master]
    

jobs:

  build staging:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone Flutter repository with stable channel
      uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: '3.3.9'
    - run: flutter doctor -v
    - run: flutter pub get
    - run: flutter build -v web --release
